model: laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K
compile: False
seed: 42

device: cuda
output_dir: "./output"

wandb: True
wandb_project:

train_dataset: 
eval_dataset:
datatype: "hf"
csv_separator: "\t"
image_col: "image"
text_col: "description"
shuffle: True

lora_rank: 32
lora_alpha: 64
lora_dropout: 0.0

batch_size: 32
gradient_accumulation_steps: 2
gradient_checkpointing: False

use_8bit_adam: False

learning_rate: 1e-4
epochs: 3
warmup: 0.05
save_interval: 5000
eval_interval: 500
eval_steps: 100
