model_name: "laion/CLIP-ViT-H-14-laion2B-s32B-b79K"
output_dir: "/clipora_output"
lora_rank: 8
gradient_accumulation_steps: 1
gradient_checkpointing: False
use_8bit_adam: False
learning_rate: 0.0005
epochs: 5
warmup: 100
save_steps: 500
instance_data_dir: "./train.csv"
image_col: "image_url"
text_col: "play_text"
csv_separator: "\t"
batch_size: 32
shuffle: True
workers: 1
wandb: True