model_name: "ViT-H-14"
pretrained: "laion2B-s32B-b79K"
compile: True
seed: 42

device: "cpu"
output_dir: "./output"

wandb: True
wanb_project: clipora

train_dataset: "./data/train.csv"
eval_dataset: "./data/val.csv"
datatype: "csv"
csv_separator: "\t"
image_col: "image"
text_col: "text"
shuffle: True

lora_rank: 16
lora_alpha: 32
lora_dropout: 0.0

batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: True

use_8bit_adam: False

learning_rate: 1e-4
epochs: 3
warmup: 0.01
save_interval: 1000
eval_interval: 1000
eval_steps: 100

