model_name: "ViT-H-14"
pretrained: "laion2B-s32B-b79K"

output_dir: "./clipora_output"

lora_rank: 32
lora_alpha: 1.0
lora_dropout: 0.0

gradient_accumulation_steps: 1
gradient_checkpointing: False

use_8bit_adam: False

learning_rate: 0.000005
epochs: 3
warmup: 0.1
save_steps: 1000
eval_interval: 1000
eval_steps: 100

instance_data_dir: "./train_data.csv"
datatype: "csv"
image_col: "s3_url"
text_col: "description"
csv_separator: "\t"
batch_size: 1
shuffle: True
workers: 0

wandb: False
wanb_project: clipora